### ISSUE TITLE
WebGL build failed

### ISSUE THREAD

**Issue by R1nge** [forcepusher/YandexGamesUnity#4]
I can't build the game after installing this plugin
I tried 16.0.0 and 16.0.1 both resulted in a build failure

Win 10, Unity 2022.3.9f1, Python 3.12.2 added to the PATH
IL2CPP - faster runtime
C++ - release
Code optimization - shorter build time
Compression - brotli

Trace
```
Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
Traceback (most recent call last):
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 3982, in <module>
    sys.exit(main(sys.argv))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 3975, in main
    ret = run(args)
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 1184, in run
    phase_post_link(options, state, wasm_target, wasm_target, target)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 2745, in phase_post_link
    phase_emscript(options, in_wasm, wasm_target, memfile)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 2773, in phase_emscript
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 937, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile)
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 327, in emscript
    glue, forwarded_data = compile_settings()
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 183, in compile_settings
    cwd=path_from_root('src'), env=env)
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 236, in run_js_tool
    return check_call(command, **kw).stdout
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 222, in check_call
    return run_process(cmd, *args, **kw)
  File "C:\Users\R1nge\Documents\UnityEngines\2022.3.9f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 106, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 64029: character maps to <undefined>

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

```

**Comment by R1nge** [comment]
After creating a new project I've confirmed that something's wrong with my project, since it has compiled
Probably, because my project is cross platform and some plugins are conflicting
